[package]
name = "ansible"
version = "0.2.0"
edition = "2024"
description = "Rust API for Ansible"
authors = ["Lxkota"]
repository = "https://github.com/Lxkota95/ansible"
license = "MIT"
readme = "README.md"

[dependencies]
anyhow = "1.0.98"
serde = "1.0.219"
serde_json = "1.0.140"
