[package]
name = "ansible"
version = "0.1.0"
edition = "2024"
description = "Rust API for Ansible"
authors = ["Lxkota"]
repository = "https://github.com/Lxkota95/ansible"
license = "MIT"
readme = "README.md"

[dependencies]
serde = "1.0.219"
